# appveyor file
# http://www.appveyor.com/docs/appveyor-yml
version: "{build}"

os: Visual Studio 2017

# Test against this version of Node.js
environment:
  nodejs_version: "12"
platform: x64

init:
  - git config --global core.autocrlf input

cache:
  - "%LOCALAPPDATA%\\Yarn"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version x64
  # install modules
  - yarn

before_build:
  - yarn lint

build_script:
  - yarn dist

test: off

branches:
  only:
  - master
  - /v\d*\.\d*\.\d*/