blank_issues_enabled: true
contact_links:
  - name: App Submission
    url: https://github.com/atomery/catalog/issues
    about: Submit new app to catalog
  - name: Email
    url: https://atomery.com/support?app=singlebox
    about: Contact the developer directly via email